name: Docker Build and Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile.build
      - requirements.txt
      - setup.sh
      - .github/workflows/main.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: woodchen
        password: ${{ secrets.ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile.build
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: woodchen/telegram-ai-bot:latest